env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:import/recommended
  - plugin:jsx-a11y/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - import
  - jsx-a11y
  - react
  - react-hooks

rules:
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: 0
  linebreak-style: 0
  react/jsx-no-constructed-context-values: 0
